version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: app
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

#Docker Networks
networks:
  laravel:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
